name: CICD

on:
  push:
    branches:
      - main
    tags: 
      - "v*.*.*"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22 
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint --if-present

      - name: Run unit tests
        run: npm test --if-present
        
  release-apk:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --include=dev

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Clean everything
        run: |
          rm -rf android/app/build
          rm -rf android/.cxx
          rm -rf node_modules/.cache
          cd android && ./gradlew clean

      # Try codegen generation with fallback
      - name: Generate Codegen artifacts
        run: |
          cd android
          # Try the new task first, fallback to old approach if it fails
          ./gradlew generateCodegenArtifactsFromSchema || \
          echo "Codegen task not available, proceeding with build"

      - name: Force autolinking regeneration
        run: |
          rm -rf android/app/build/generated/autolinking
          npx react-native config

      # Pre-build step to ensure all dependencies are properly configured
      - name: Pre-build configuration
        run: |
          cd android
          ./gradlew :app:preBuild

      - name: Build release APK
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Upload APK to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: android/app/build/outputs/apk/release/app-release.apk
